package pl.tachograf2;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.*;
import android.media.projection.MediaProjectionManager;
import android.os.*;
import android.graphics.Color;
import android.view.Gravity;
import android.widget.*;
import java.util.Locale;

public class MainActivity extends Activity {
 static final int CAPTURE=401;
 TextView speed,mode,ocr,status,display,times,cardInfo,vehicleInfo,activityLog,warning;
 Button captureBtn; SharedPreferences prefs;
 long driveMs,totalMs,restMs,todayDriveMs,weekDriveMs,twoWeekDriveMs,lastTick,zeroSince;
 double distanceKm; int currentSpeed; boolean driving;
 String driver="BRAK KARTY",driverId="---",plate="---",activity="ODPOCZYNEK";
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("tachograf",0);load();lastTick=System.currentTimeMillis();buildUi();IntentFilter f=new IntentFilter(ScreenCaptureService.ACTION_SPEED);if(Build.VERSION.SDK_INT>=33)registerReceiver(receiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(receiver,f);if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},55);new Handler(Looper.getMainLooper()).post(tick);}
 TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.rgb(220,255,160));v.setTextSize(z);v.setPadding(8,7,8,7);return v;} LinearLayout.LayoutParams lp(){return new LinearLayout.LayoutParams(-1,-2);} Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void buildUi(){ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(12,12,12,24);r.setBackgroundColor(Color.rgb(8,9,10));TextView brand=tv("TACHOGRAF2 • v2.0",25);brand.setGravity(Gravity.CENTER);brand.setTypeface(null,1);r.addView(brand,lp());TextView sub=tv("DIGITALNY TACHOGRAF • TRUCKERS OF EUROPE 3",12);sub.setGravity(Gravity.CENTER);r.addView(sub,lp());display=tv("00:00\n0 km/h\nODPOCZYNEK",25);display.setGravity(Gravity.CENTER);display.setBackgroundColor(Color.rgb(24,29,24));display.setPadding(10,18,10,18);r.addView(display,lp());speed=tv("Prędkość: 0 km/h",18);r.addView(speed,lp());mode=tv("Aktywność: ODPOCZYNEK",17);r.addView(mode,lp());status=tv("● Odczyt ekranu: NIEAKTYWNY",13);r.addView(status,lp());ocr=tv("OCR: ---",11);r.addView(ocr,lp());captureBtn=btn("📡 START ODCZYTU EKRANU");captureBtn.setOnClickListener(v->startCapture());r.addView(captureBtn,lp());Button stop=btn("⏹ STOP ODCZYTU");stop.setOnClickListener(v->stopCapture());r.addView(stop,lp());
  r.addView(tv("⚙️ AKTYWNOŚĆ TACHOGRAFU",17),lp());LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.HORIZONTAL);Button j=btn("🚛 JAZDA"),p=btn("🔧 PRACA"),d=btn("📦 DYSPOZYCJA"),o=btn("🛌 ODPOCZYNEK");m.addView(j,new LinearLayout.LayoutParams(0,-2,1));m.addView(p,new LinearLayout.LayoutParams(0,-2,1));m.addView(d,new LinearLayout.LayoutParams(0,-2,1));m.addView(o,new LinearLayout.LayoutParams(0,-2,1));r.addView(m,lp());j.setOnClickListener(v->setActivity("JAZDA"));p.setOnClickListener(v->setActivity("PRACA"));d.setOnClickListener(v->setActivity("DYSPOZYCJA"));o.setOnClickListener(v->setActivity("ODPOCZYNEK"));
  r.addView(tv("💳 KARTA KIEROWCY",17),lp());cardInfo=tv("Kierowca: BRAK KARTY\nID: ---",14);r.addView(cardInfo,lp());LinearLayout cb=new LinearLayout(this);Button ins=btn("WŁÓŻ / ZMIEŃ KARTĘ"),rem=btn("WYJMIJ KARTĘ");cb.addView(ins,new LinearLayout.LayoutParams(0,-2,1));cb.addView(rem,new LinearLayout.LayoutParams(0,-2,1));r.addView(cb,lp());ins.setOnClickListener(v->cardDialog());rem.setOnClickListener(v->{driver="BRAK KARTY";driverId="---";updateCard();save();});
  r.addView(tv("🚛 POJAZD / ZESTAW",17),lp());vehicleInfo=tv("Rejestracja: ---\nNumer zestawu: ---",14);r.addView(vehicleInfo,lp());Button veh=btn("USTAW POJAZD");veh.setOnClickListener(v->vehicleDialog());r.addView(veh,lp());
  r.addView(tv("⏱ CZASY JAZDY I ODPOCZYNKU",17),lp());times=tv("",14);r.addView(times,lp());r.addView(tv("⚠️ KONTROLA LIMITÓW",17),lp());warning=tv("Brak aktywnych ostrzeżeń.",14);r.addView(warning,lp());r.addView(tv("📋 HISTORIA AKTYWNOŚCI",17),lp());activityLog=tv("Brak zapisanych zdarzeń.",13);r.addView(activityLog,lp());
  Button print=btn("🧾 RAPORT / WYDRUK TACHOGRAFU");print.setOnClickListener(v->report());r.addView(print,lp());Button reset=btn("🔄 NOWA TRASA — WYZERUJ LICZNIKI");reset.setOnClickListener(v->resetRoute());r.addView(reset,lp());r.addView(tv("ℹ️ TRYB RP\nSymulator cyfrowego tachografu dla Truckers of Europe 3. Prędkość może być odczytywana z HUD przez przechwytywanie ekranu. Nie jest to certyfikowany tachograf drogowy.",12),lp());sc.addView(r);setContentView(sc);updateAll();}
 void setActivity(String a){if(!activity.equals(a)){addLog("Zmiana aktywności: "+a);}activity=a;driving=a.equals("JAZDA");if(driving)zeroSince=0;mode.setText("Aktywność: "+a);save();}
 void cardDialog(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this);n.setHint("Imię i nazwisko kierowcy");EditText id=new EditText(this);id.setHint("ID karty kierowcy");x.addView(n);x.addView(id);new AlertDialog.Builder(this).setTitle("💳 KARTA KIEROWCY").setView(x).setNegativeButton("ANULUJ",null).setPositiveButton("ZAPISZ",(a,w)->{driver=n.getText().toString().trim();driverId=id.getText().toString().trim();if(driver.isEmpty())driver="KIEROWCA";if(driverId.isEmpty())driverId="ID-001";updateCard();addLog("Włożono kartę kierowcy: "+driver);save();}).show();}
 void vehicleDialog(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText p=new EditText(this);p.setHint("Numer rejestracyjny");EditText z=new EditText(this);z.setHint("Numer zestawu");x.addView(p);x.addView(z);new AlertDialog.Builder(this).setTitle("🚛 POJAZD").setView(x).setNegativeButton("ANULUJ",null).setPositiveButton("ZAPISZ",(a,w)->{plate=p.getText().toString().trim();if(plate.isEmpty())plate="---";String set=z.getText().toString().trim();vehicleInfo.setText("Rejestracja: "+plate+"\nNumer zestawu: "+(set.isEmpty()?"---":set));addLog("Ustawiono pojazd: "+plate);save();}).show();}
 void updateCard(){cardInfo.setText("Kierowca: "+driver+"\nID: "+driverId);}
 void startCapture(){MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);startActivityForResult(m.createScreenCaptureIntent(),CAPTURE);} void stopCapture(){stopService(new Intent(this,ScreenCaptureService.class));status.setText("● Odczyt ekranu: ZATRZYMANY");captureBtn.setText("📡 START ODCZYTU EKRANU");}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==CAPTURE&&c==RESULT_OK&&data!=null){Intent i=new Intent(this,ScreenCaptureService.class);i.putExtra("code",c);i.putExtra("data",data);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);status.setText("● Odczyt ekranu: AKTYWNY");captureBtn.setText("🟢 ODCZYT AKTYWNY");}}
 final BroadcastReceiver receiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){currentSpeed=Math.max(0,i.getIntExtra("speed",0));speed.setText("Prędkość: "+currentSpeed+" km/h");ocr.setText("OCR: "+i.getStringExtra("text")+" • Pewność: "+i.getIntExtra("confidence",0)+"%");if(currentSpeed>0&&!driving)setActivity("JAZDA");else if(currentSpeed==0&&driving&&zeroSince==0)zeroSince=System.currentTimeMillis();}};
 final Runnable tick=new Runnable(){public void run(){long now=System.currentTimeMillis(),dt=Math.max(0,now-lastTick);lastTick=now;if(driving&&currentSpeed==0&&zeroSince>0&&now-zeroSince>=2000)setActivity("ODPOCZYNEK");if(driving){driveMs+=dt;totalMs+=dt;todayDriveMs+=dt;weekDriveMs+=dt;twoWeekDriveMs+=dt;distanceKm+=(double)currentSpeed*dt/3600000.0;restMs=0;}else restMs+=dt;if(restMs>=45*60*1000L&&driveMs>0){driveMs=0;restMs=0;addLog("45 min przerwy — reset jazdy ciągłej");}updateAll();save();new Handler(Looper.getMainLooper()).postDelayed(this,500);}};
 void updateAll(){if(times==null)return;display.setText(new java.text.SimpleDateFormat("HH:mm",Locale.getDefault()).format(new java.util.Date())+"\n"+currentSpeed+" km/h\n"+activity);times.setText("Jazda ciągła: "+fmt(driveMs)+" / 04:30:00\nPozostało do przerwy: "+fmt(Math.max(0,270*60*1000L-driveMs))+"\nJazda dzisiaj: "+fmt(todayDriveMs)+" / 09:00:00\nPrzerwa/odpoczynek: "+fmt(restMs)+"\nTydzień: "+fmt(weekDriveMs)+" / 56:00:00\n2 tygodnie: "+fmt(twoWeekDriveMs)+" / 90:00:00\nDystans: "+String.format(Locale.US,"%.2f km",distanceKm));StringBuilder w=new StringBuilder();if(driveMs>=270*60*1000L)w.append("🟥 PRZEKROCZONA JAZDA 4:30 — WYMAGANA PRZERWA 45 MIN\n");else if(driveMs>=255*60*1000L)w.append("🟨 ZBLIŻASZ SIĘ DO LIMITU 4:30\n");if(todayDriveMs>=9*3600000L)w.append("🟥 PRZEKROCZONA JAZDA DZIENNA 9 H\n");if(weekDriveMs>=56*3600000L)w.append("🟥 PRZEKROCZONY LIMIT TYGODNIOWY 56 H\n");if(twoWeekDriveMs>=90*3600000L)w.append("🟥 PRZEKROCZONY LIMIT 2 TYGODNI 90 H\n");warning.setText(w.length()==0?"🟢 Brak aktywnych ostrzeżeń.":w.toString());}
 void addLog(String s){if(activityLog==null)return;String old=activityLog.getText().toString();String t=new java.text.SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new java.util.Date());String n=t+" • "+s+"\n"+old;activityLog.setText(n.substring(0,Math.min(5000,n.length())));}
 void report(){new AlertDialog.Builder(this).setTitle("🧾 WYDRUK TACHOGRAFU").setMessage("KIEROWCA: "+driver+"\nID: "+driverId+"\nPOJAZD: "+plate+"\n\nJAZDA DZISIAJ: "+fmt(todayDriveMs)+"\nJAZDA TYGODNIOWA: "+fmt(weekDriveMs)+"\nJAZDA 2 TYGODNIE: "+fmt(twoWeekDriveMs)+"\nDYSTANS: "+String.format(Locale.US,"%.2f km",distanceKm)+"\n\nAKTYWNOŚĆ: "+activity+"\n\nRaport symulatora RP.").setPositiveButton("OK",null).show();}
 void resetRoute(){new AlertDialog.Builder(this).setTitle("🔄 NOWA TRASA").setMessage("Wyzerować czasy i dystans?").setNegativeButton("ANULUJ",null).setPositiveButton("WYZERUJ",(a,w)->{driveMs=totalMs=restMs=todayDriveMs=weekDriveMs=twoWeekDriveMs=0;distanceKm=0;currentSpeed=0;driving=false;activity="ODPOCZYNEK";lastTick=System.currentTimeMillis();addLog("Nowa trasa — wyzerowano liczniki");save();updateAll();Toast.makeText(this,"Nowa trasa — liczniki wyzerowane",Toast.LENGTH_SHORT).show();}).show();}
 void save(){if(prefs==null)return;prefs.edit().putLong("drive",driveMs).putLong("total",totalMs).putLong("rest",restMs).putLong("today",todayDriveMs).putLong("week",weekDriveMs).putLong("two",twoWeekDriveMs).putFloat("dist",(float)distanceKm).putBoolean("driving",driving).putString("driver",driver).putString("driverId",driverId).putString("plate",plate).putString("activity",activity).apply();}
 void load(){driveMs=prefs.getLong("drive",0);totalMs=prefs.getLong("total",0);restMs=prefs.getLong("rest",0);todayDriveMs=prefs.getLong("today",0);weekDriveMs=prefs.getLong("week",0);twoWeekDriveMs=prefs.getLong("two",0);distanceKm=prefs.getFloat("dist",0);driving=prefs.getBoolean("driving",false);driver=prefs.getString("driver","BRAK KARTY");driverId=prefs.getString("driverId","---");plate=prefs.getString("plate","---");activity=prefs.getString("activity",driving?"JAZDA":"ODPOCZYNEK");zeroSince=0;}
 String fmt(long x){long s=x/1000,h=s/3600,m=s%3600/60,z=s%60;return String.format(Locale.US,"%02d:%02d:%02d",h,m,z);}
 @Override protected void onPause(){save();super.onPause();}@Override protected void onStop(){save();super.onStop();}@Override protected void onDestroy(){save();try{unregisterReceiver(receiver);}catch(Exception e){}super.onDestroy();}
}
